name: GPT-4 Code Review

permissions:
  contents: read
  pull-requests: write

on: # 언제 실행할지
  pull_request: # PR이 올라오면
    types: [ opened, reopened, synchronize ] # PR 생성 , 재생성 , 커밋같은 동기화 작업이 있을때

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-4
          max_tokens: 10000
