name: GPT-4 Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read prompt file
        id: prompt
        uses: juliangruber/read-file-action@v1
        with:
          path: ./code-review-prompt.txt

      - name: Run GPT-4 Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-4
          PROMPT: 당신은 OOP 원칙을 따르고 성능과 효율을 중시하는 클린코드를 추구하는 훌륭한 시니어 개발자입니다.  코드 리뷰를 잘합니다. 코드에 대한 솔직한 피드백을 해주세요. 
