name: GPT-4 Code Revie

on:
  pull_request:
    branches:
      - '*'

permissions:
  pull-requests: write
  contents: read

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GPT-4 Code Review
        uses: anc95/ChatGPT-CodeReview@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-4
          LANGUAGE: Korean
