name: GPT-4 Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  gpt_code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run GPT-4 Code Review
      run: |
        npm install
        node index.js
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}